---
driver:
  name: vagrant
provisioner:
  name: chef_solo
  cookbook_files_glob: "**/*"
  require_chef_omnibus: 11.18.12
  solo_rb:
    verify_api_cert: true
    ssl_verify_mode: :verify_peer
    log_level: :info
platforms:
  - name: centos-7.1
suites:
  - name: install
    run_list:
      - recipe[kitchen-test-helper]
      - recipe[supervisord::add]
    attributes:
      workorder:
        rfcCi:
          ciAttributes:
            http_port: "9001"
            http_username: "admin"
            http_password: "admin"
            program_config: ""

