# default - Default attribute values for the pack

default['spark-v2']['spark_custom_download'] = '$OO_LOCAL{nexus}'
default['spark-v2']['force_spark_reinstall'] = 'false'
default['spark-v2']['hadoop_dir'] = '/opt/hadoop'
default['spark-v2']['hadoop_dir'] = '/opt/hadoop'
default['spark-v2']['hive_dir'] = '/opt/hive'
default['spark-v2']['spark_base'] = '/opt'
default['spark-v2']['spark_tmp_dir'] = '/work'
default['spark-v2']['spark_version'] = ' '
default['spark-v2']['spark_master'] = ''
default['spark-v2']['worker_cores'] = '2'
default['spark-v2']['worker_memory'] = '2g'
default['spark-v2']['master_opts'] = '[]'
default['spark-v2']['worker_opts'] = '[]'
default['spark-v2']['spark_config'] = '{}'
default['spark-v2']['enable_ganglia'] = 'false'
default['spark-v2']['ganglia_servers'] = ''
default['spark-v2']['enable_thriftserver'] = 'false'
default['spark-v2']['thrift_server_port'] = '10000'
default['spark-v2']['thrift_ldap_server'] = ''
default['spark-v2']['thrift_ldap_domain'] = ''
default['spark-v2']['is_client_only'] = 'false'
default['spark-v2']['enable_historyserver'] = 'true'
default['spark-v2']['spark_events_dir'] = '/work/events'
default['spark-v2']['history_server_port'] = '18080'
default['spark-v2']['use_yarn'] = 'false'
