# update_config - Update the Centrify Configuration
#
# This recipe updates the Centrify configuration.

Chef::Log.info("Running #{node['app_name']}::update_config")

configName = node['app_name']
configNode = node[configName]

cent_cache_path = Chef::Config[:file_cache_path]

centrify_config_file = "/etc/centrifydc/centrifydc.conf"
centrify_config_orig_file = centrify_config_file + ".orig"

# remote_file produces way too much output in debug environments
bash "backup_config" do
    user "root"
    code <<-EOF
        if [[ -e "#{centrify_config_orig_file}" ]]; then
          : # File already exists
        else
          cp -p "#{centrify_config_file}" "#{centrify_config_orig_file}"
        fi
    EOF
    not_if "/bin/ls #{centrify_config_orig_file}"
end

# This override file is used to ensure that all users are
# using bash for their shell
file "/etc/centrifydc/passwd.ovr" do
  content "+:::::::/bin/bash"
  mode    '0644'
  owner   'root'
  group   'root'
end

# Create the configuration from the original settings.
bash "generate_config" do
  user    "root"
  code <<-EOF
  echo "# This file is generated by OneOps.  Do not modify manually." > "#{centrify_config_file}"
  echo "" >> "#{centrify_config_file}"

  cat "#{centrify_config_orig_file}" |grep -v "^#" |grep -v "^$" > "#{centrify_config_file}"

  echo "" >> "#{centrify_config_file}"
  echo "#Generated by OneOps" >> "#{centrify_config_file}"
  echo "secedit.system.access.maximumpasswordage 60" >> "#{centrify_config_file}"
  echo "secedit.system.access.minimumpasswordage 1" >> "#{centrify_config_file}"
  echo "secedit.system.access.lockoutduration 30" >> "#{centrify_config_file}"
  echo "secedit.system.access.lockoutbadcount 13" >> "#{centrify_config_file}"
  echo "pam.password.expiry.warn 5" >> "#{centrify_config_file}"
  
  echo "adclient.clients.threads 200" >> "#{centrify_config_file}"
  echo "adclient.clients.threads.max 1000" >> "#{centrify_config_file}"
  echo "adclient.use.all.cpus true" >> "#{centrify_config_file}"
  echo "adclient.clients.listen.backlog 500" >> "#{centrify_config_file}"

  echo "nss.group.override /etc/centrifydc/passwd.ovr" >> "#{centrify_config_file}"
  EOF
end
