#VAGRANTFILE_API_VERSION = "2"

Vagrant.configure("2") do |config|
  config.vm.box = 'windows-2016'
  config.vm.guest = :windows
  config.vm.provider "virtualbox" do |v|
    v.gui = false
  end

  config.vm.communicator = "winrm"
  config.winrm.timeout = 24000
  config.winrm.max_tries = 20

  config.winrm.host = '127.0.0.1'
  config.winrm.username = 'vagrant'
  config.winrm.password = 'vagrant'


  config.vm.provision :chef_solo do |chef|
  chef.log_level         = :debug
  chef.cookbooks_path = [".."]
  chef.add_recipe("chocopackage::add")

  chef.json = {
    "chocopackage": {
      "chocolatey_package_details": "{ \"notepadplusplus\":\"6.9.2\"}",
      "chocolatey_package_source": "https://chocolatey.org/api/v2/"
    },
    "workorder": {
      "services": {
        "mirror": {
          "vagrant": {
            "ciAttributes": {
              "mirrors": "{ \"chocolatey-repo\":\"https://chocolatey.org/api/v2/\"}"
            }
          }
        }
      },
      "cloud": {
        "nsId": 110104,
        "ciAttributes": {
          "adminstatus": "active",
          "auth": ""
        },
        "ciName": "vagrant",
      }
    }
  }
end

end
